#' visualize_res
#'
#' compute similarities between topics generated by new models and topics in original models
#'
#' @include rlda_c.R
#' @param r a rlda object
#' @exportMethod visual_res
#'

setGeneric("visual_res", function(r)standardGeneric("visual_res"))
setMethod("visual_res",
          signature(r = "rlda"),
          function (r) {

            if(length(r@gamma_list) == 0)
            {
              stop("must run fit first")
            }

            if(length(r@similarity_mat_list) != 0)
            {
              for (i in 1:length(r@similarity_mat_list))
                image(r@similarity_mat_list[[i]])
            }
          }
          )
